### PR TITLE
fixed to work with empty expires metadata

### PR DESCRIPTION
**Pull request by adrian-herscu-ge**

### CODE REVIEW

**Comment by JuanCarlosGonzalez** [comment]
Hi.

Thanks for your PR. In order to merge it, please provide a unit test for fix. 

Best regards,

Juan Carlos González

**Comment by adrian-herscu-ge** [comment]
Although not tested, the existing unit tests should work as before since this particular use-case was not covered. This is what I can do for now ;)

**Review by JuanCarlosGonzalez — COMMENTED** [review]
Hi.

Thanks for your help. Please, could you clarify your fix?. Why is not valid your first approach?.

Best regards,

**Comment by adrian-herscu-ge** [comment]
My first fix seemed to work at first.
After second attempt, it still failed with NPE.
Sorry, do not have enough time to dig any deeper -- just made it work for my simple scenario, uploading a test report to an S3 bucket.

**Comment by JuanCarlosGonzalez** [comment]
Ok. 

However this is not enough for merging your second approach without further reasoning. I'll close this PR until this can be clarified.

Thanks for your help

**Pull request closed without merging**
